# Generated by ChatGPT on 2025-12-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_orderitem_is_ready"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("UNPAID", "Nieopłacone"), ("PAID", "Opłacone")],
                default="UNPAID",
                max_length=10,
                verbose_name="Status płatności",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Data płatności"),
        ),
        migrations.AddField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Data wydania"),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Data anulowania"),
        ),
    ]
