# Generated by Django 6.0 on 2025-12-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
    ]
