# Generated by Django 6.0 on 2025-12-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_history_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_price', models.DecimalField(decimal_places=2, default=0.5, max_digits=5, verbose_name='Cena opakowania (EUR)')),
            ],
            options={
                'verbose_name': 'Ustawienia Strony',
                'verbose_name_plural': 'Ustawienia Strony',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='is_takeaway',
            field=models.BooleanField(default=False, verbose_name='Na wynos'),
        ),
    ]
