# Generated by Django 6.0 on 2025-12-08 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_order_is_takeaway'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.AddField(
            model_name='category',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Jeśli ustawisz grafikę, będzie użyta zamiast koloru.', null=True, upload_to='category_backgrounds/', verbose_name='Grafika tła kafelka'),
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, help_text='Np. #ffcc00. Zostaw puste, jeśli używasz grafiki.', max_length=7, validators=[django.core.validators.RegexValidator(message='Wpisz poprawny kolor HEX, np. #ffcc00', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Kolor kafelka (HEX)'),
        ),
    ]
