# Generated by Django 6.0 on 2025-12-09 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Np. #ffcc00. Zostaw puste, aby użyć koloru kategorii lub domyślnego.', max_length=7, validators=[django.core.validators.RegexValidator(message='Wpisz poprawny kolor HEX, np. #ffcc00', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Kolor belki (HEX)'),
        ),
    ]
