# Generated by Django 6.0 on 2025-12-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_product_image_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Opcjonalne zdjęcie wyświetlane w kiosku', null=True, upload_to='product_images/', verbose_name='Zdjęcie produktu'),
        ),
    ]
