# Generated by Django 6.0 on 2025-12-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, help_text='Liczba sztuk dostępna w magazynie.', verbose_name='Stan magazynu'),
        ),
    ]
