# Generated by Django 6.0 on 2025-12-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_block_when_zero',
            field=models.BooleanField(default=False, help_text='Jeśli zaznaczone: gdy stan spadnie do 0 produkt zostanie zablokowany w kiosku, a po uzupełnieniu stanu automatycznie odblokowany.', verbose_name='Auto blokada przy stanie 0'),
        ),
    ]
