# Generated by Django 6.0 on 2025-12-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_product_auto_block_when_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Koszt zakupu / przygotowania jednej sztuki.', max_digits=6, verbose_name='Koszt jednostkowy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena sprzedaży'),
        ),
    ]
