# Generated by Django 6.0 on 2025-12-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_payment_and_cancel_fields'),
        ('core', '0017_product_cost_price_alter_product_price'),
    ]

    operations = [
    ]
