# Generated by Django 6.0 on 2025-12-13 19:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_order_cancelled_at_remove_order_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data anulowania'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Opłacone'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data płatności'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='core.product', verbose_name='Produkt'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Ilość'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ready_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Ilość gotowa'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Koszt jednostkowy (snapshot)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Cena jednostkowa (snapshot)'),
        ),
        migrations.AddField(
            model_name='product',
            name='margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Opcjonalnie. Jeśli zostawisz 0, marżę można liczyć z ceny i kosztu.', max_digits=5, verbose_name='Marża (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='prep_time_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Jeśli puste, używana jest dotychczasowa metoda wyliczania czasu.', null=True, verbose_name='Czas przygotowania (sek)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nowe'), ('ACCEPTED', 'Przyjęte'), ('IN_PROGRESS', 'W przygotowaniu'), ('READY', 'Gotowe'), ('DONE', 'Wydane'), ('CANCELLED', 'Anulowane'), ('PAID', 'Opłacone'), ('UNPAID', 'Nieopłacone')], default='NEW', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order', verbose_name='Zamówienie'),
        ),
    ]
