# Generated by Django 6.0 on 2025-12-13 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_order_cancelled_at_order_is_paid_order_paid_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ready_qty',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='margin_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prep_time_seconds',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nowe'), ('READY', 'Gotowe'), ('DONE', 'Wydane')], default='NEW', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='Zamówienie'),
        ),
    ]
