# Generated by Django 6.0 on 2025-12-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_order_cancelled_at_remove_order_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Nieopłacone'), ('NEW', 'Nowe'), ('READY', 'Gotowe'), ('DONE', 'Wydane')], db_index=True, default='NEW', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Odznacz, aby zablokować zamawianie tego produktu w kiosku.', verbose_name='Dostępny w kiosku'),
        ),
    ]
