# Generated by Django 6.0 on 2025-12-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_order_created_at_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_packaging_fee',
            field=models.BooleanField(default=True, help_text='Zaznacz, jeśli do tego produktu ma być doliczana opłata przy zamówieniu na wynos.', verbose_name='Opłata za opakowanie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Opcjonalne zdjęcie wyświetlane w kiosku. Zostanie automatycznie zmniejszone do 800px.', null=True, upload_to='product_images/', verbose_name='Zdjęcie produktu'),
        ),
    ]
