# Generated by Django 6.0 on 2025-12-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_order_cancel_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa dodatku')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena dodatku')),
                ('is_available', models.BooleanField(default=True, verbose_name='Dostępny?')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='is_customizable',
            field=models.BooleanField(default=False, verbose_name='Edytowalny (dodatki)?'),
        ),
        migrations.AddField(
            model_name='product',
            name='possible_ingredients',
            field=models.ManyToManyField(blank=True, to='core.ingredient', verbose_name='Możliwe dodatki'),
        ),
    ]
