# Generated by Django 6.0 on 2025-12-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_ingredient_product_is_customizable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='core.ingredient', verbose_name='Wybrane dodatki'),
        ),
    ]
