# Generated by Django 6.0 on 2025-12-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_orderitem_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='can_cashier_deliver',
            field=models.BooleanField(default=True, help_text="Jeśli odznaczone, przycisk 'Wydaj' będzie ukryty dla kasjera (produkt musi wydać kuchnia).", verbose_name='Kasjer może wydać?'),
        ),
    ]
