# Generated by Django 6.0 on 2025-12-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_product_can_cashier_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='can_kitchen_deliver',
            field=models.BooleanField(default=True, help_text='Jeśli odznaczone, produkt nie będzie widoczny na ekranie kuchni (KDS).', verbose_name='Kuchnia może wydać?'),
        ),
    ]
