# Generated by Django 6.0 on 2025-12-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_product_can_kitchen_deliver'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_delivery_before_payment', models.BooleanField(default=True, help_text='Jeśli odznaczone, kasjer nie będzie mógł wydać produktu (kliknąć +1/Done) dopóki zamówienie jest NIEOPŁACONE.', verbose_name='Zezwalaj na wydawanie przed zapłatą')),
            ],
            options={
                'verbose_name': 'Ustawienia systemu',
                'verbose_name_plural': 'Ustawienia systemu',
            },
        ),
    ]
