# Generated by Django 6.0 on 2025-12-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_globalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa stanowiska')),
                ('station_type', models.CharField(choices=[('KIOSK', 'Kiosk samoobsługowy'), ('KITCHEN', 'Ekran kuchenny (KDS)'), ('CASHIER', 'Stanowisko kasjerskie')], default='KIOSK', max_length=10, verbose_name='Typ stanowiska')),
                ('slug', models.SlugField(unique=True, verbose_name='Identyfikator URL (slug)')),
            ],
            options={
                'verbose_name': 'Stanowisko (Kiosk/Kuchnia/Kasa)',
                'verbose_name_plural': 'Stanowiska',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='limit_availability',
            field=models.ManyToManyField(blank=True, help_text='Zostaw puste, aby produkt był dostępny WSZĘDZIE. Wybierz konkretne stacje, jeśli chcesz ograniczyć widoczność.', to='core.station', verbose_name='Ogranicz dostępność do...'),
        ),
    ]
