# Generated by Django 6.0 on 2025-12-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_station_product_limit_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='allow_delivery_before_payment',
            field=models.BooleanField(default=True, help_text='Dotyczy tylko stanowisk typu KASA. Jeśli odznaczone, blokuje przyciski wydawania dla nieopłaconych zamówień.', verbose_name='Zezwalaj na wydawanie przed zapłatą'),
        ),
    ]
