# Generated by Django 6.0 on 2025-12-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_station_allow_delivery_before_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa alergenu')),
                ('code', models.CharField(blank=True, help_text='Np. GL, ORZ', max_length=10, verbose_name='Kod/Skrót')),
            ],
            options={
                'verbose_name': 'Alergen',
                'verbose_name_plural': 'Alergeny',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.ManyToManyField(blank=True, help_text='Zaznacz alergeny obecne w tym produkcie.', to='core.allergen', verbose_name='Alergeny'),
        ),
    ]
