# Generated by Django 6.0 on 2025-12-17 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_allergen_product_allergens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Imię / Nick')),
                ('pin', models.CharField(blank=True, help_text='Zostaw puste dla logowania bez hasła', max_length=4, null=True, verbose_name='PIN (opcjonalny)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('can_work_cashier', models.BooleanField(default=True, verbose_name='Może pracować na Kasie')),
                ('can_work_kitchen', models.BooleanField(default=True, verbose_name='Może pracować na Kuchni')),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to='core.station', verbose_name='Wydano na stacji'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee', verbose_name='Wydane przez (Lider)'),
        ),
        migrations.AddField(
            model_name='order',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='helped_orders', to='core.employee', verbose_name='Zespół wydający'),
        ),
    ]
