# Generated by Django 6.0 on 2025-12-17 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_employee_order_station_order_delivered_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered_by',
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_by_bar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bar_orders', to='core.employee', verbose_name='Wydane przez (Bar/Kasa)'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_by_kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_orders', to='core.employee', verbose_name='Wydane przez (Kuchnia)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to='core.station', verbose_name='Ostatnia stacja'),
        ),
        migrations.AlterField(
            model_name='order',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='helped_orders', to='core.employee', verbose_name='Zespół wydający (pomocnicy)'),
        ),
    ]
