# Generated by Django 6.0 on 2025-12-18 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_order_delivered_by_order_delivered_by_bar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='team_members',
        ),
        migrations.AddField(
            model_name='order',
            name='bar_team',
            field=models.ManyToManyField(blank=True, related_name='bar_orders_team', to='core.employee', verbose_name='Zespół Baru (pomocnicy)'),
        ),
        migrations.AddField(
            model_name='order',
            name='kitchen_team',
            field=models.ManyToManyField(blank=True, related_name='kitchen_orders_team', to='core.employee', verbose_name='Zespół Kuchni (pomocnicy)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_by_bar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bar_orders_leader', to='core.employee', verbose_name='Wydane przez (Lider Baru/Kasy)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_by_kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_orders_leader', to='core.employee', verbose_name='Wydane przez (Lider Kuchni)'),
        ),
    ]
