# Generated by Django 6.0 on 2025-12-18 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_order_team_members_order_bar_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee', verbose_name='Wykonane przez'),
        ),
    ]
