# Generated by Django 6.0 on 2025-12-31 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_orderitem_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Gotówka'), ('CARD', 'Karta'), ('ONLINE', 'Online'), ('OTHER', 'Inne')], max_length=10, null=True, verbose_name='Metoda płatności'),
        ),
        migrations.CreateModel(
            name='StationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Czas zdarzenia')),
                ('action', models.CharField(choices=[('LOGIN', 'Logowanie'), ('LOGOUT', 'Wylogowanie'), ('LEADER', 'Zmiana Lidera'), ('ITEM_DONE', 'Wydanie Produktu'), ('ORDER_PAID', 'Opłacenie'), ('ORDER_SPLIT', 'Podział Rachunku'), ('OTHER', 'Inne')], max_length=20, verbose_name='Typ akcji')),
                ('details', models.TextField(blank=True, verbose_name='Szczegóły')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee', verbose_name='Pracownik')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.order', verbose_name='Powiązane zamówienie')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.station', verbose_name='Stacja')),
            ],
            options={
                'verbose_name': 'Log Systemowy',
                'verbose_name_plural': 'Logi Systemowe',
                'ordering': ['-timestamp'],
            },
        ),
    ]
