# Generated by Django 6.0 on 2026-01-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_order_payment_method_stationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='allow_kiosk_card_payment',
            field=models.BooleanField(default=False, help_text='Zaznacz, jeśli ten kiosk ma terminal płatniczy.', verbose_name='Kiosk: Płatność kartą na miejscu'),
        ),
    ]
