# Generated by Django 6.0 on 2026-01-01 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_station_allow_kiosk_card_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='auto_report_time',
            field=models.TimeField(default=datetime.time(22, 0), verbose_name='Godzina automatycznej wysyłki'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='report_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do raportów dziennych'),
        ),
        migrations.AddField(
            model_name='station',
            name='last_report_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data ostatniego raportu'),
        ),
    ]
