# Generated by Django 6.0 on 2026-01-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_globalsettings_auto_report_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='auto_report_time',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='report_email',
        ),
        migrations.RemoveField(
            model_name='station',
            name='last_report_date',
        ),
    ]
