# Generated by Django 6.0 on 2026-01-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_globalsettings_auto_report_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='stock_safe_limit',
            field=models.IntegerField(default=20, help_text='Ilość, powyżej której stan magazynowy wyświetli się na zielono.', verbose_name='Próg bezpieczny magazynu (zielony)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='stock_warning_limit',
            field=models.IntegerField(default=5, help_text='Ilość, poniżej której stan magazynowy wyświetli się na pomarańczowo.', verbose_name='Próg ostrzegawczy magazynu (pomarańczowy)'),
        ),
    ]
