# Generated by Django 6.0 on 2026-01-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_globalsettings_stock_safe_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_card',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
