# Generated by Django 6.0 on 2026-01-03 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_order_payment_card_order_payment_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa półproduktu')),
                ('stock', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Stan magazynowy')),
                ('unit', models.CharField(default='szt', max_length=10, verbose_name='Jednostka (kg, l, szt)')),
            ],
            options={
                'verbose_name': 'Półprodukt',
                'verbose_name_plural': 'Półprodukty',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='uses_raw_materials',
            field=models.BooleanField(default=False, verbose_name='Używa półproduktów?'),
        ),
        migrations.CreateModel(
            name='ProductRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Ilość zużywana')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='core.product')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rawmaterial', verbose_name='Półprodukt')),
            ],
        ),
    ]
