# Generated by Django 6.0 on 2026-01-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_rawmaterial_product_uses_raw_materials_productrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='auto_logout_time',
            field=models.TimeField(blank=True, help_text='Godzina, o której system wymusi wylogowanie wszystkich pracowników (raz dziennie).', null=True, verbose_name='Godzina auto-wylogowania'),
        ),
    ]
