# Generated by Django 6.0 on 2026-01-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_station_auto_logout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='auto_logout_time',
            field=models.TimeField(blank=True, help_text='Godzina, o której system wymusi wylogowanie wszystkich pracowników.', null=True, verbose_name='Godzina auto-wylogowania'),
        ),
    ]
